version: '3.1'

services:

  client:
    image: "zherebykh/clicca.agency.client:v1"
    container_name: "worker"
    env_file:
      - worker.env

  server:
    image: "zherebykh/clicca.agency.server:v1"
    container_name: "server"
    env_file:
      - server.env
    ports:
      - 8080:8080  

